cooldown-seconds: 60
# Op players will not have a cooldown


messages:
  teleport-success: "<green>You have been safely teleported.</green>"
  teleport-fail: "<red>No safe location could be found.</red>"
  no-permission: "<red>You do not have permission to perform this action.</red>"
  cooldown-wait: "<red>Please wait <yellow><seconds>s</yellow> before teleporting again.</red>"
  config-reloaded: "<green>The configuration has been successfully reloaded.</green>"
  world-not-found: "<red>The specified world could not be located.</red>"

gui:
  overworld:
    material: GRASS_BLOCK
    name: "&aOverworld"
    lore:
      - "&7Teleport to the"
      - "&7main survival world."
    slot: 11
    world: world
    range: 5500

  nether:
    material: NETHERRACK
    name: "&cNether"
    lore:
      - "&7A perilous realm"
      - "&7of fire and danger."
    slot: 13
    world: world_nether
    range: 2300

  end:
    material: END_STONE
    name: "&dThe End"
    lore:
      - "&7A mysterious void..."
      - "&7Do you dare venture forth?"
    slot: 15
    world: world_the_end
    range: 5500
